//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AF_Clipper_Dll.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AF_Clipper_Dll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportUserCommandType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///            #region CLIP Configuration
        ///      [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string All_Commandes {
            get {
                return ResourceManager.GetString("All_Commandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportUserEntityType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///            #region Tôles
        ///            
        ///            {
        ///                IEn [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string All_Entities {
            get {
                return ResourceManager.GetString("All_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportCustomizedFormulaEventType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///            ITransaction transacti [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string All_Events {
            get {
                return ResourceManager.GetString("All_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.1.4;2.1.5.
        /// </summary>
        public static string Almcam_Version {
            get {
                return ResourceManager.GetString("Almcam_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AlmaCAM_Clipper_8.
        /// </summary>
        public static string Clipper_Almacam_Database_Name {
            get {
                return ResourceManager.GetString("Clipper_Almacam_Database_Name", resourceCulture);
            }
        }
    }
}
