//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCamTrainingTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmaCamTrainingTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportCustomizedFormulaEventType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///            ITransaction transacti [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string _event {
            get {
                return ResourceManager.GetString("_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BUTTON {
            get {
                object obj = ResourceManager.GetObject("BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.Processor;
        ///using Wpm.Implement.ComponentEditor;  // ouverture de fenetres de selection almacam
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportUserCommandType : ScriptModelCustomization, ISc [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string CommandesV2 {
            get {
                return ResourceManager.GetString("CommandesV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportUserEntityType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///        
        ///            
        ///		  //preparation du dictionnaire //
        ///            / [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Entities3 {
            get {
                return ResourceManager.GetString("Entities3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FONDExport {
            get {
                object obj = ResourceManager.GetObject("FONDExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
